// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Victor França
/* global console, process */

// Generates src/generated/{types,schemas}.ts from the normative JSON Schemas in schemas/.
// The six schema files are the source of truth; this script is the only thing that writes the
// generated TypeScript. Run via `npm run gen:types --workspace @francav/spec`.
//
// For type generation the six files are merged into one in-memory document with every cross-file
// `$ref` rewritten from its absolute `$id` to a local `#/$defs/...` pointer, so json-schema-to-
// typescript never touches the network and each named type is declared exactly once. The published
// schema objects (schemas.ts) keep their original absolute `$id`/`$ref` form, byte-identical to the
// files under schemas/.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";
import prettier from "prettier";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(__dirname, "..");
const schemasDir = path.join(pkgRoot, "schemas");
const outDir = path.join(pkgRoot, "src", "generated");

const SPDX = "// SPDX-License-Identifier: Apache-2.0\n// Copyright 2026 Victor França\n";
const GENERATED = "// AUTOGENERATED by scripts/gen-types.mjs from schemas/*.json — do not edit.\n";

// (schema filename, exported const identifier in schemas.ts)
const FILES = [
  ["classification.schema.json", "classificationSchema"],
  ["policy.schema.json", "policySchema"],
  ["runtime-profile.schema.json", "runtimeProfileSchema"],
  ["contract.schema.json", "contractSchema"],
  ["compile-options.schema.json", "compileOptionsSchema"],
  ["compiler-result.schema.json", "compilerResultSchema"],
];

const ID_BASE = "https://spec.dpg.dev/l1/v1/";

/** Rewrite every absolute L1 `$ref` to a local `#/$defs/...` pointer. */
function localizeRefs(node) {
  if (Array.isArray(node)) return node.map(localizeRefs);
  if (node && typeof node === "object") {
    const out = {};
    for (const [key, value] of Object.entries(node)) {
      if (key === "$ref" && typeof value === "string" && value.startsWith(ID_BASE)) {
        const hash = value.indexOf("#");
        out[key] = hash === -1 ? "#" : value.slice(hash);
      } else {
        out[key] = localizeRefs(value);
      }
    }
    return out;
  }
  return node;
}

async function main() {
  const loaded = [];
  for (const [file, constName] of FILES) {
    const raw = await readFile(path.join(schemasDir, file), "utf8");
    loaded.push({ file, constName, json: JSON.parse(raw) });
  }

  // --- types.ts: merge all $defs into one local-ref document, compile once. ---
  const mergedDefs = {};
  for (const { json } of loaded) {
    for (const [name, def] of Object.entries(json.$defs ?? {})) {
      if (mergedDefs[name]) {
        throw new Error(`Duplicate $def name across schema files: ${name}`);
      }
      mergedDefs[name] = def;
    }
  }
  // Reference every merged $def from the bundle root so json-schema-to-typescript emits each named
  // type exactly once (it only generates types reachable from the root). The wrapper interface
  // itself is stripped from the output below — it is a codegen artifact, not part of the L1 surface.
  const rootProps = {};
  for (const name of Object.keys(mergedDefs)) {
    rootProps[name] = { $ref: `#/$defs/${name}` };
  }
  const bundle = localizeRefs({
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: `${ID_BASE}_bundle.json`,
    title: "DpgL1Bundle",
    description: "Internal codegen bundle — not published.",
    type: "object",
    additionalProperties: false,
    properties: rootProps,
    $defs: mergedDefs,
  });

  const compiled = await compile(bundle, "DpgL1Bundle", {
    additionalProperties: false,
    bannerComment: "",
    declareExternallyReferenced: true,
    format: false,
    enableConstEnums: false,
  });

  // Drop the internal wrapper interface (its JSDoc block + declaration); keep only the L1 types.
  // Anchored on the unique wrapper description so it cannot swallow neighbouring declarations.
  const types = compiled.replace(
    /\/\*\*\n \* Internal codegen bundle[\s\S]*?\nexport interface DpgL1Bundle \{[\s\S]*?\n\}\n/,
    "",
  );

  await mkdir(outDir, { recursive: true });
  await writeGenerated(path.join(outDir, "types.ts"), `${SPDX}${GENERATED}\n${types}`);

  // --- schemas.ts: inline each normative file verbatim (absolute $ids preserved). ---
  let schemasOut = `${SPDX}${GENERATED}\n`;
  const registryEntries = [];
  for (const { constName, json } of loaded) {
    schemasOut += `export const ${constName} = ${JSON.stringify(json, null, 2)} as const;\n\n`;
    registryEntries.push(`  ${JSON.stringify(json.$id)}: ${constName},`);
  }
  schemasOut +=
    "/** All six L1 schemas keyed by their canonical $id. */\n" +
    "export const l1Schemas = {\n" +
    registryEntries.join("\n") +
    "\n} as const;\n";
  await writeGenerated(path.join(outDir, "schemas.ts"), schemasOut);

  console.log(`Generated ${path.relative(pkgRoot, outDir)}/{types,schemas}.ts`);
}

/** Format with the repo's prettier config so the generated files pass `prettier --check`. */
async function writeGenerated(file, content) {
  const config = (await prettier.resolveConfig(file)) ?? {};
  const formatted = await prettier.format(content, { ...config, parser: "typescript" });
  await writeFile(file, formatted);
}

main().catch((error) => {
  console.error("gen-types failed:", error);
  process.exitCode = 1;
});
